version: 0.2

phases:
  install:
    commands:
     - echo Entering install phase...

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - chmod +x gradlew

  build:
    commands:
     - echo Build started on `date`
     - gradle build
artifacts:
  files:
    - build/libs/dms.jar
