version: 0.2

phases:
  install:
    commands:
     - echo Entering install phase...
     - add-apt-repository ppa:cwchien/gradle
     - apt-get update -y
     - apt upgrade gradle -y

  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - chmod +x gradlew

  build:
    commands:
     - echo Build started on `date`
     - gradle build
artifacts:
  files:
    - 'build/libs/*.jar'
